# Generated by Django 4.0.6 on 2022-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įmonės pavadinimas pvz UAB "Terinta"', max_length=200, verbose_name='Pavadinimas')),
                ('address', models.CharField(help_text='Įmonės adresas registru sistemoje', max_length=200, verbose_name='Adresas')),
                ('VATcode', models.CharField(help_text='Įmonės PVM moketojo kodas', max_length=200, verbose_name='PVM kodas')),
                ('companyCode', models.CharField(help_text='Įmonės kodas', max_length=200, verbose_name='Imones kodas')),
                ('discountForCompany', models.CharField(help_text='Nuolaidos dydis taikomas imonei', max_length=200, verbose_name='Nuolaida imonei')),
            ],
        ),
    ]
