# Generated by Django 4.0.6 on 2022-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0003_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='show',
            field=models.CharField(blank=True, choices=[('r', 'Rodyti'), ('n', 'Nerodyti')], default='n', help_text='pasirinkti ar rodyti tinklalapyje (iskart nustatomas nerodyti', max_length=1),
        ),
    ]
