# Generated by Django 4.0.6 on 2022-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0005_alter_customercompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='supplier',
            field=models.ManyToManyField(help_text='parinkite galimus tiekejus siai prekei', null=True, related_name='store_item', to='storeDatabase.supplier'),
        ),
    ]
