# Generated by Django 4.0.6 on 2022-07-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0008_storeitem_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='backgroundImage',
            field=models.ImageField(null=True, upload_to='websiteMainImages', verbose_name='Background paveikslelis'),
        ),
    ]
