# Generated by Django 4.0.6 on 2022-07-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0009_websiteinfo_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='show',
            field=models.BooleanField(blank=True, choices=[('r', 'Rodyti'), ('n', 'Nerodyti')], default=False, help_text='pasirinkti ar rodyti tinklalapyje (iskart nustatomas nerodyti', max_length=1),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='name_field1',
            field=models.CharField(default='Musu maistas', help_text='Pakeicia apie mus pastraipos pavadinima', max_length=30, verbose_name='Apie mus pastraipos pavadinimas'),
        ),
    ]
