# Generated by Django 4.0.6 on 2022-07-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0010_alter_storeitem_show_alter_websiteinfo_name_field1'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='recepto pavadinimas', max_length=200, verbose_name='Pavadinimas')),
                ('text', models.TextField(help_text='Recepto aprasymas', max_length=400, verbose_name='Recepto aprasymas')),
                ('picture', models.ImageField(help_text='ikelkite paveiksleli, geriausia, kad jo ratio butu 16:9', null=True, upload_to='itemImages', verbose_name='Recepto paveikslelis')),
                ('show', models.BooleanField(blank=True, choices=[(True, 'Rodyti'), (False, 'Nerodyti')], default=False, help_text='pasirinkti ar rodyti tinklalapyje (iskart nustatomas nerodyti', max_length=1)),
            ],
            options={
                'verbose_name': 'Receptas',
                'verbose_name_plural': 'Receptai',
            },
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='picture',
            field=models.ImageField(help_text='ikelkite paveiksleli, geriausia, kad jo ratio butu 16:9', null=True, upload_to='itemImages', verbose_name='Paveikslelis'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='show',
            field=models.BooleanField(blank=True, choices=[(True, 'Rodyti'), (False, 'Nerodyti')], default=False, help_text='pasirinkti ar rodyti tinklalapyje (iskart nustatomas nerodyti', max_length=1),
        ),
    ]
