# Generated by Django 4.0.6 on 2022-07-27 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0011_recipesitem_alter_storeitem_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 27, 22, 1, 57, 657276, tzinfo=utc), verbose_name='Sukurimo data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipesitem',
            name='publications',
            field=models.ManyToManyField(to='storeDatabase.storeitem'),
        ),
        migrations.AddField(
            model_name='recipesitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Paskutini karta atnaujinta'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 27, 22, 2, 6, 584994, tzinfo=utc), verbose_name='Sukurimo data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Paskutini karta atnaujinta'),
        ),
    ]
