# Generated by Django 4.0.6 on 2022-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0014_websiteinfo_contact_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompany',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipesitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='google_maps_link',
            field=models.TextField(help_text='google maps zemelapio nuoroda(embed url)', max_length=400, verbose_name='Google maps link'),
        ),
    ]
