# Generated by Django 4.0.6 on 2022-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0015_alter_customercompany_id_alter_recipesitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesitem',
            name='products',
            field=models.ManyToManyField(help_text='parinkite prekes kurios ieina i si recepta', null=True, related_name='store_item', to='storeDatabase.storeitem'),
        ),
    ]
