# Generated by Django 4.0.6 on 2022-08-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0016_recipesitem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesitem',
            name='related_products',
        ),
        migrations.AlterField(
            model_name='recipesitem',
            name='products',
            field=models.ManyToManyField(help_text='parinkite prekes kurios ieina i si recepta', null=True, related_name='recipe_items', to='storeDatabase.storeitem'),
        ),
    ]
