# Generated by Django 4.0.6 on 2022-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0017_remove_recipesitem_related_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Vardas')),
                ('email', models.CharField(max_length=40, verbose_name='Elektroninis pastas')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Telefono numeris')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='Atsiliepimas')),
            ],
        ),
    ]
