# Generated by Django 4.0.6 on 2022-08-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0019_alter_reviews_options_alter_recipesitem_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
