# Generated by Django 4.0.6 on 2022-08-22 12:39

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0020_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='facebook_page_link',
            field=models.TextField(default=django.utils.timezone.now, help_text='facebook puslapio nuoroda', max_length=40, verbose_name='Facebook page link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.EmailValidator(message='Įveskite teisingą elektroninio pašto adresą.')], verbose_name='Elektroninis pastas'),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Telefonas turėtų būti įvestas formatu: '+xxxx'. Galima įvesti iki 15 skaičių.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono numeris'),
        ),
    ]
