# Generated by Django 4.0.6 on 2022-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeDatabase', '0021_websiteinfo_facebook_page_link_alter_review_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinfo',
            name='facebook_page_link',
            field=models.CharField(help_text='facebook puslapio nuoroda', max_length=40, verbose_name='Facebook page link'),
        ),
    ]
